#!/bin/bash

#$1 is the name of the file

# check that the number of arguments is 1 (Step 1)
if (("$#" != 1));
then
    echo Number of arguments is not equal to 1
    echo You inputted $# arguemnts
    exit 1
fi

# check that the file exists (Step 1)
if !(test -r $1);
then
    echo File does not exist
    exit 1
fi
# extract all of the Reader Messages (R) (Step 1)
echo "Extracting Reader Messages"
grep "\[[0-9];[0-9][0-9]mR" $1 > $1.Reader

# add time range to end of file. (Step 3)
startTime=`head -n 1 $1.Reader | cut -b 11-27 | sed 's/\.//'`
endTime=`tail -n 1 $1.Reader | cut -b 11-27 | sed 's/\.//'`
printf "Time Span: %.2f\n" "$(($endTime-$startTime))e-6" >> $1.Reader

# extract all of the Printer Messages (P)  (Step 1)
echo "Extracting Summary Printer Messages"
grep "^\[[0-9];[0-9][0-9]mP" $1 > $1.Printer

# add time range to end of file. (Step 3)
startTime=`head -n 1 $1.Printer | cut -b 11-27 | sed 's/\.//'`
endTime=`tail -n 1 $1.Printer | cut -b 11-27 | sed 's/\.//'`
printf "Time Span: %.2f\n" "$(($endTime-$startTime))e-6" >> $1.Printer

#find the number of machines (Step 2)
machineList=`grep "^\[[0-9];[0-9][0-9]m[0-5]" $1 | cut -b '8' | sort -u`

# extract each machine messages (Step 2)
for machine in $machineList;
do
    echo "Extracting Machine $machine Messages"
    grep "^\[[0-9];[0-9][0-9]m$machine" $1 > $1.Machine$machine
done